all:
	gcc -Wall -c classement.c -o classement.o
	gcc -Wall -c mes_semaphores.c -o mes_semaphores.o
	gcc -Wall classement.o mes_semaphores.o -o main

clean:
	$(RM) *.o *~ classement mes_semaphores main