all:
	gcc -Wall exo1fils.c -o exo1fils
	gcc -Wall exo1pere.c -o exo1pere
	gcc -Wall attrape_signaux.c -o attrape_signaux
	gcc -Wall recouvrant_attrape_signaux.c -o recouvrant_attrape_signaux
	gcc -Wall question1.c -o question1
	gcc -Wall question2.c -o question2
	gcc -Wall question3.c -o question3
	gcc -Wall question3_recouvrant.c -o question3_recouvrant
clean:
	$(RM) *.o *~ exo1fils exo1pere attrape_signaux recouvrant_attrape_signaux question1 question2 question3 question3_recouvrant
