all:
	gcc -Wall interception.c -o interception
	gcc -Wall timer.c -o timer
	gcc -Wall pont.c -o pont
	gcc -Wall recouvrant_pont.c -o recouvrant_pont
	gcc -Wall timer++.c -o timer++
	gcc -Wall recouvrant_timer++.c -o recouvrant_timer++
clean:
	$(RM) *.o *~ interception timer pont recouvrant_pont timer++ recouvrant_timer++